### getting the main page

GET http://localhost:3000/


### create

POST http://localhost:3000/create
Content-Type: application/json

{
    "username": "Andres",
    "password":"acvb"
}
### login
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "andres",
    "password":"acvb"
}

### logout

POST http://localhost:3000/logout
